apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteOnce                 # Single node can mount
  resources:
    requests:
      storage: 10Gi                 # Request 10Gi
  storageClassName: gp2             # AWS EBS GP2 type